Snap install
rdswift/picard-docs pull request #76
Opened 2020-12-14 10:34 UTC by phw

### Summary

This is a…

- [ ] Correction
- [x] Addition
- [ ] Restructuring
- [ ] Minor / simple change (like a typo)
- [ ] Other

### Reason for the Change
The Snap version for Picard has been updated and is now on par with the Flatpak version.

### Description of the Change

Update Linux instructions to provide Snap as an alternative installation method. In general restructure the Linux instructions a bit and also mention distribution packages (which likely still are the most common way to install Picard on Linux).

### Additional Action Required

Linux with its special way of handling software distribution warrants some more detailed descriptions. But In general we could detail the install instructions for macOS and Windows more as well. E.g. for Windows we could describe the individual options (installer, portable, Windows 10 store).

So for the future we might aim for a general Download & Install page, but this then links to platform specific pages with more details.

2020-12-14 17:46 UTC, rdswift requested changes
This looks good, and you even updated the translation file.  Thank-you!

2020-12-14 17:46 UTC, rdswift commented on _locale/fr/LC_MESSAGES/getting_started/download.po
> +": index: `Installation à partir du référentiel de packages de votre "
Need to remove the space between the first colon and 'index', and the space between the second colon and the backtick.

2020-12-14 22:20 UTC, rdswift requested changes

2020-12-14 22:20 UTC, rdswift commented on _locale/fr/LC_MESSAGES/getting_started/download.po
> +"distribution <pair: install; Paquet Linux> `"
Need to remove extra spaces.  Every time I use Google Translate it changes all the spacing (and sometimes the backticks) around the restructured-text directives.

```suggestion
":index:`Installation à partir du référentiel de packages de votre "
"distribution <pair: install; Paquet Linux>`"
```

2020-12-15 06:52 UTC, phw commented on _locale/fr/LC_MESSAGES/getting_started/download.po
> +"distribution <pair: install; Paquet Linux> `"
Oh yes, good catch. Was hard to spot locally (using poedit). One needs to be careful with the Google translate results

2020-12-15 06:52 UTC, merged